# Generated by Django 4.2 on 2023-04-30 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('duration', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('start_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('end_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('course_fee', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_semesters', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('std_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('std_cnic', models.CharField(blank=True, max_length=50, null=True)),
                ('father_cnic', models.CharField(blank=True, max_length=50, null=True)),
                ('std_no', models.CharField(blank=True, max_length=50, null=True)),
                ('father_no', models.CharField(blank=True, max_length=50, null=True)),
                ('qualification', models.CharField(max_length=50)),
                ('dob', models.CharField(blank=True, max_length=50, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_degree_issued', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.course')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
