# Generated by Django 4.2 on 2023-04-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_course_student_delete_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='total_semesters',
        ),
        migrations.AddField(
            model_name='course',
            name='semesters',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
