# Generated by Django 4.2 on 2023-04-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_student_total_semesters_course_semesters'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
