# Generated by Django 4.2 on 2023-04-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='abscents',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
