# Generated by Django 4.2 on 2023-04-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_attendance_abscents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='abscents',
            field=models.PositiveSmallIntegerField(default=2),
            preserve_default=False,
        ),
    ]
