# Generated by Django 4.2 on 2023-04-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_schedule_student_duration_student_semesters_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveSmallIntegerField()),
                ('end_year', models.PositiveSmallIntegerField()),
                ('course', models.CharField(max_length=50, unique=True)),
                ('semester', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('exam_name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('date_time', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
